from src.middlewares.delete_messages import DeleteMessagesMiddleware
from src.middlewares.album import MediaGroupMiddleware
from src.middlewares.skip_updates_from_adminchat import SkipAdminchatUpdates
from src.middlewares.null import NullMiddleware
from src.middlewares.prediction_message_del_keyboard import PredictionMessageDeleteKeyboardMiddleware

